### ISSUE TITLE
Besoin d'heberegement de logiciels libres?

### ISSUE THREAD

**Issue by pierreozoux** [tgalopin/enpremiereligne.fr#10]
Salut!

tres bonne initiative, bravo!

Une personne avait mis en place ce [discourse](https://www.entraidecoronavirus.fr/t/en-premiere-ligne-soyons-presents-pour-ceux-en-premiere-ligne/63) mais votre site est tres bien dans un autre registre :)

Juaste un petit coucou, pour vous dire que si vous avez besoin d'hebergement d'appli opensource, genre jitsi/Nextcloud/RocketChat pour vous ou qui que ce soit, on peut aussi aider.

Une fois lu, vous pouvez fermer l'issue.

**Comment by tgalopin** [comment]
Bonjour Pierre,

C'est gentil de proposer, merci ! Pour le moment nous n'avons pas le besoin mais si il apparait plus tard, je viendrais vous pinger ici :) .
