### ISSUE TITLE
Permettre d'avoir plusieurs zones d'action

### ISSUE THREAD

**Issue by Gladear** [tgalopin/enpremiereligne.fr#12]
Bonjour,

Je tiens d'abord à vous féliciter pour cette initiative. J'espère qu'elle permettra d'aider le personnel soignant et les personnes qui en ont besoin.

Ceci est une demande de fonctionnalité.
J'aimerai pouvoir indiquer que je peux intervenir sur plusieurs code postaux.
J'habite à Lyon, dans le 1er arrondissement. Si j'en crois le code source, le système ne pourra me faire correspondre qu'avec des demandeurs d'aide du 1er arrondissement de Lyon, alors que je suis à deux pas du 4ème et du 6ème !

Je propose que l'utilisateur puisse indiquer plusieurs code postaux, mais il doit aussi être possible pour le système de vérifier si un code postal n'est pas trop loin d'un autre, ce qui aurait l'avantage d'éviter d'avoir à changer la base de données.

Bonne soirée à vous !

**Comment by tgalopin** [comment]
C'est une très bonne idée :) . Si quelqu'un a un peu de temps pour le faire, je peux guider sans soucis.

**Comment by froulet** [comment]
Bonjour,
Merci pour cette excellente initiative.
Vous venez d’obtenir une grande visibilité grâce à la vidéo de Brut, ce qui est une bonne chose :) !
J’ai un peu de temps libre pour travailler sur le site si nécessaire.
Quelle seraient les priorités ? Puis-je par exemple commencer par cette issue ?
Courage à vous tous !

**Comment by tgalopin** [comment]
Bonjour @froulet,

Oui, tout à fait, si vous avez le temps de travailler sur ceci, n'hésitez pas !

**Comment by tgalopin** [comment]
@froulet j'ai implémenté une stratégie différente au final, et plus pratique pour tout le monde : on a calculé le zip code le plus proche d'un autre zip code et on l'inclut aussi dans le matching, avec un score plus faible.

Si vous souhaitez continuer cette PR, vous pouvez mais pas sûr que l'utilité existe encore. Si vous souhaitez contrinuber, https://github.com/tgalopin/enpremiereligne.fr/issues/4 est hyper importante :) !

**Comment by Gladear** [comment]
Super !
Merci pour votre réactivité :blush:
