### ISSUE TITLE
Provide guidance on translations

### ISSUE THREAD

**Issue by dillanmann** [tgalopin/enpremiereligne.fr#22]
Hi,
Is it possible to provide guidance on how we can help with translations? I note that a translation folder exists, but there is no instruction on the format of translations.

I'd like to provide English translations with a potential view to forking this for use in the UK but am unsure whree to start.

Thanks, and I must really commend you on the project, it's a truly excellent idea.

**Comment by tgalopin** [comment]
Hello @dillanmann !

I'm glad you like our project! It was currently made with a French focus and it wasn't made with translations in mind. However, if you can help us translate it in English, it's definitely possible :) !

The first thing we can do is chat about this by email: titouan@enpremiereligne.fr :) .

**Comment by tgalopin** [comment]
Hello @dillanmann !

We are going to start an internationalized initiative on this project: feel free to reach me by e-mail to discuss it more if you're interested :) !

**Comment by dillanmann** [comment]
Hey Titouan - have emailed you, happy to continue the conversation on email. Shall I keep this ticket open or close it for now?

**Comment by tgalopin** [comment]
Let's close it, thanks!
