### ISSUE TITLE
[Feature] Create a static image for the needs of volunteers

### ISSUE THREAD

**Issue by tgalopin** [tgalopin/enpremiereligne.fr#43]
We would like to post on a regular basis (probably weekly) a static image on our social networks about where we need volunteers depending on our database. For example:

https://twitter.com/en1ereligne/status/1243157326447742976

Having a generator of such image in the back-office would help us a lot.

**Comment by Lucas-C** [comment]
I'm starting to work on this

**Comment by Lucas-C** [comment]
_Work in progress_ :
![2020-04-03 16_40_10-Mozilla Firefox](https://user-images.githubusercontent.com/925560/78372678-db84a100-75c9-11ea-96bc-83b3553b4c11.png)

**Comment by Lucas-C** [comment]
I submitted a PR : https://github.com/tgalopin/enpremiereligne.fr/pull/45

Could I have some feedback on it please ?

How do you recommend to handle the `DEPARTMENT_FILL_COLOR` / `DEPARTMENT_COLORING_THRESHOLD` configuration values ?
